### ISSUE TITLE
Ability to exclude certain strings from getting removed when using clean parameter

### ISSUE THREAD

**Issue by takahser** [biesbjerg/ngx-translate-extract#105]
Currently, when using `--clean`, obsolete strings get removed when merging, which is desired most of the times. However, in some cases, such as when using dynamic translation keys, the `ngx-translate-extract` script, of course, won't be able to evaluate that these are actually valid.

Quick example:

```
<p> {{ 'staticTranslationString' | translate }} </p> <!-- won't get removed -->
<p> {{ dynamicTranslationString | translate }} </p> <!-- will get removed -->
```

Let's assume, `dynamicTranslationString` is assigned to `dynamicValue` in the `*.ts` controller. Now, the translation file would look something like this:

```
{
  "staticTranslationString": "foo",
  "dynamicValue": "bar"
}
```

Now, ofc the `dynamicValue` will get removed when running the script. If we could find a way to prevent this from happening, maybe by providing a whitelist or something like that, that would be great.

**Comment by Ismaestro** [comment]
updates?

**Comment by ranemloc** [comment]
The solution should be easy, declare these translations keys as constants in your code using a marker (read the 'Mark strings for extraction using a marker function' in the projects readme), you can declare your own marker if, like us, you do not like the one provided by the library (we already use _ for lodash).

Since the extract command will find these keys in the code thanks to the marker, they will no longer be removed from the JSON.

Hope it helps

**Comment by biesbjerg** [comment]
I agree with @ranemloc. You should maintain a list of words you don't want cleaned in your code, wrapped by the marker function.

```ts
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

marker('keep');
marker('me2');
marker([
  'or', 
  'as', 
  'array'
]);
```
