### ISSUE TITLE
Support for Pug?

### ISSUE THREAD

**Issue by blissi** [biesbjerg/ngx-translate-extract#107]
Hallo,
do you plan to support parsing Pug templates?

Thanks,
Steven

**Comment by h0m1c1de** [comment]
Works for me -p /**/*.pug

**Comment by biesbjerg** [comment]
No sorry, not at this time.

**Comment by markbb33** [comment]
@blissi I know this is old, but as @h0m1c1de pointed out, the extractor does work as long as you use the translate pipe instead of the directive.

So this works: `h1 {{ "Some text" | translate }}`

However this does not: `h1(translate) Some text`

I wrestled with this for a while as I considered it a reason not to use pug format as the later is definitely more readable, however I ended deciding that the pipe format is easier to visually see whether I missed a translation, espacially if you have a more complex example like: `button.progress-button.cs-button.large.primary(type='submit', [disabled]='!form!.valid') Login`

Don't forget to add your pug files to the extract command as well: `ngx-translate-extract --input ./src --patterns=\"/**/*.{html,pug,ts}\"`
