### ISSUE TITLE
Certain HTML causes the wrong key to be extracted

### ISSUE THREAD

**Issue by buren** [biesbjerg/ngx-translate-extract#15]
Thank you for a nice package 😃  👍  Certainly saved us a ton of time! 

---

When parsing this HTML [(source code)](https://github.com/justarrived/just-match-web/blob/d7b216ab4e5c178ab7b32b9ce465568d4b3088ac/src/app/views/user/user-settings/user-details/user-details.component.html#L34):

```html
<input class="form-control material-input" id="phone" name="phone" type="text" (focus)="serverValidationErrors.phone = ''" placeholder="{{'user.settings.form.phone.placeholder' | translate}}"  [formControl]="settingsForm.controls['phone']">
```

this JSON gets returned:
```json
{
  "'\" placeholder=\"{{'user.settings.form.phone.placeholder": "",
}
```

`node` version: 6.7.0
`ng2-translate-extract` version: 0.6.0
`npm` version: 3.10.8

__Reproduce__:

```
$ git clone git@github.com/justarrived/just-match-web.git
$ cd just-match-web
$ npm run extract-translations
$ cat used_i18n.json # File with invalid keys
```

Maybe this is whats need to be updated, https://github.com/biesbjerg/ng2-translate-extract/blob/master/src/parsers/directive.parser.ts#L51-L53.

I'm sorry that I can't provide any more details than the above. Please let me know if there are any else I can do.

Thanks!

**Comment by biesbjerg** [comment]
Thanks!

It's actually this regexp that is the cause of the bug: https://github.com/biesbjerg/ng2-translate-extract/blob/master/src/parsers/pipe.parser.ts#L18

I'm afraid this is a bit above my current regexp level, so any help fixing it is welcome!

**Comment by biesbjerg** [comment]
Regex that fixes the issues, but introduces another bug, where strings with other quote types are not extracted correctly: https://regex101.com/r/zUdtjF/1

**Comment by buren** [comment]
Thanks @biesbjerg for getting back so quickly.

I'm afraid this is also a bit over my head in terms of regexp-foo 😳 Will try to think of someone that could help out.

In the meantime, I could just do some minor post-processing to fix those occurrences :)

**Comment by biesbjerg** [comment]
Cool:-) 

Long term I would like to use angular's template parser, but that's a completely other dragon to slay...

**Comment by crain** [comment]
I have the same issue. I could apply the following workaround:

Instead of:
`<a md-fab color="accent" [routerLink]="['create']" title="{{'Create customer' | translate}}"></a>`

I switched the position of routerLink to:
`<a md-fab color="accent" title="{{'Create customer' | translate}}" [routerLink]="['create']"></a>`

So it helps if you move any attribute which is using single quotes after the translate pipe.

**Comment by cvaliere** [comment]
here you go: (['"`])((?:(?!(?<!\\)\1).)*)\1\s*\|\s*translate

**Comment by biesbjerg** [comment]
@cvaliere that regexp breaks a bunch of tests.

![image](https://cloud.githubusercontent.com/assets/230182/24538660/e4104b90-15ea-11e7-866a-f277133d3a8c.png)

**Comment by cvaliere** [comment]
woups, sorry, I thought all the test cases were on the link you provided (https://regex101.com/r/zUdtjF/1)

I'll try to find a good one

**Comment by cvaliere** [comment]
I got confused between PHP and JS regex.
It appears that my regex was working on PHP, with a negative lookbehind, but negative lookbehind isn't implemented in JS :(

So, I found a new one, PR is here: https://github.com/biesbjerg/ngx-translate-extract/pull/31

Note that I needed to change also the test, because the quote needed to be double escaped

hope it's ok this time!
