### ISSUE TITLE
not able to extract strings 

### ISSUE THREAD

**Issue by nileshzala005** [biesbjerg/ngx-translate-extract#163]
/@biesbjerg/ngx-translate-extract/dist/utils/ast-helpers.js:76
        return expression.elements.reduce((result, element) => {
                                   ^

TypeError: Cannot read property 'reduce' of undefined

**Comment by DavidCMeier** [comment]
same error here :_(

**Comment by DavidCMeier** [comment]
I checked the code and the problem is in "isArrayLiteralExpression". i modify in the code and use: 

in ast-helper, function getStringsFromExpression(expression):
`if(expression.elements) return expression.elements.reduce((result, element) => {`

that is working, but is never enter on the method because never exist elements on expression.

**Comment by jochenjonc** [comment]
See #166, probably it can be temporarily solved in the same manner.

**Comment by biesbjerg** [comment]
Could someone please provide a full example of a file that results in the error when trying to extract strings from it?

**Comment by biesbjerg** [comment]
Closing since I cannot reproduce.
