### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined - v6.0.3

### ISSUE THREAD

**Issue by QuentinFchx** [biesbjerg/ngx-translate-extract#173]
Hello,

I ran into the following issue when extracting translations (I upgraded from v4.0):

```
TypeError: Cannot read property 'reduce' of undefined
at Object.getStringsFromExpression (/node_modules/@biesbjerg/ngx-translate-extract/dist/utils/ast-helpers.js:99:36)
at callExpressions.forEach (/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/service.parser.js:26:47)
at Array.forEach (<anonymous>)
at classDeclarations.forEach (/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/service.parser.js:21:29)
at Array.forEach (<anonymous>)
at ServiceParser.extract (/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/service.parser.js:16:27)
at parsers.forEach (/node_modules/@biesbjerg/ngx-translate-extract/dist/cli/tasks/extract.task.js:85:46)
at Array.forEach (<anonymous>)
at getFiles.forEach (/node_modules/@biesbjerg/ngx-translate-extract/dist/cli/tasks/extract.task.js:84:30)
at Array.forEach (<anonymous>)
```

I seems than the following code triggered the issue (I simplified it and removed sensitive data, so it might not reproduce it entirely):

`"@biesbjerg/ngx-translate-extract": "6.0.3"`

```typescript
class Foo {
    private foo(): Observable<boolean> {
        return from(this.service.confirm(this.translateService.instant('key'))).pipe(
            switchMap(a =>
                a
                    ? this.service.bar().pipe(
                          tap(() => {})),
                          map(() => false)
                      )
                    : of(false)
            )
        );
    }
}
```

When I extracted `this.translateService.instant('key')` into its own variable `const tr = this.translateService.instant('key')` and then `from(this.service.confirm(tr))` it worked.
I've seen ast_helpers have been recently changed, might it be the cause of that issue?

<details>
<summary>I think this is the expression that was passed to `getStringsFromExpression` if it helps</summary>

```
NodeObject {
  pos: 10631,
  end: 10980,
  flags: 0,
  modifierFlagsCache: 0,
  transformFlags: 0,
  parent:
   NodeObject {
     pos: 10517,
     end: 10990,
     flags: 0,
     modifierFlagsCache: 0,
     transformFlags: 0,
     parent:
      NodeObject {
        pos: 10502,
        end: 10991,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 0,
        parent: [NodeObject],
        kind: 231,
        expression: [Circular] },
     kind: 192,
     expression:
      NodeObject {
        pos: 10517,
        end: 10630,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 0,
        parent: [Circular],
        kind: 190,
        expression: [NodeObject],
        name: [IdentifierObject] },
     arguments: [ [Circular], pos: 10631, end: 10980 ] },
  kind: 192,
  expression:
   IdentifierObject {
     pos: 10631,
     end: 10653,
     flags: 0,
     modifierFlagsCache: 0,
     transformFlags: 0,
     parent: [Circular],
     escapedText: 'switchMap' },
  arguments:
   [ NodeObject {
       pos: 10654,
       end: 10966,
       flags: 0,
       modifierFlagsCache: 0,
       transformFlags: 0,
       parent: [Circular],
       kind: 198,
       parameters: [Array],
       equalsGreaterThanToken: [TokenObject],
       body: [NodeObject] },
     pos: 10654,
     end: 10966 ] }
```
</details>

Thank you in advance :)

**Comment by torinthiel** [comment]
I'm pretty sure it's enough to have `.pipe` with anything to trigger this error.
That is
 `this.translateService.get('key').pipe(filter( v => v)).subscribe(...)` triggers the error, while
`this.translateService.get('key').pipe().subscribe(...)` does not.

**Comment by macjohnny** [comment]
We faced the same issue with `@biesbjerg/ngx-translate-extract@4.2.0`. 
```
@biesbjerg/ngx-translate-extract/dist/utils/ast-helpers.js:76
        return expression.elements.reduce((result, element) => {
                                        ^
TypeError: Cannot read property 'reduce' of undefined
```

After debugging / analyzing the issue I found the following cause:

The problem occurs at this line in the source file:

https://github.com/biesbjerg/ngx-translate-extract/blob/8fd157802b4a80f3bf04238bbf77c0a579791db5/src/utils/ast-helpers.ts#L89-L90

Since the `package.json` lists both `@phenomnomnominal/tsquery` and `typescript` as `dependencies`
https://github.com/biesbjerg/ngx-translate-extract/blob/v4.2.0/package.json#L86-L97,
in our project with
```
typescript@3.5.3
@biesbjerg/ngx-translate-extract@4.2.0
```
we get the following directory structure:
```
node_modules/
  | -- @biesbjerg/ngx-translate-extract/ (4.2.0)
         | -- node_modules/ 
                       ...
                | -- typescript/ (3.7.2)
                       ...
  | -- @phenomnomnominal/tsquery (3.0.0)
  | -- typescript (3.5.3)  
```

now the service-parser (https://github.com/biesbjerg/ngx-translate-extract/blob/v4.2.0/src/parsers/service.parser.ts) uses `@phenomnomnominal/tsquery` to parse the source code:
https://github.com/biesbjerg/ngx-translate-extract/blob/8fd157802b4a80f3bf04238bbf77c0a579791db5/src/parsers/service.parser.ts#L13
@phenomnomnominal/tsquery will traverse its parent `node_modules` to find the `/node_modules/typescript`, and hence uses `typescript@3.5.3` to parse the source file.

the service-parser then uses the `ast-helpers.ts`, 
https://github.com/biesbjerg/ngx-translate-extract/blob/8fd157802b4a80f3bf04238bbf77c0a579791db5/src/utils/ast-helpers.ts#L89-L90
which in turn uses the `isArrayLiteralExpression` function of `typescript`
https://github.com/biesbjerg/ngx-translate-extract/blob/8fd157802b4a80f3bf04238bbf77c0a579791db5/src/utils/ast-helpers.ts#L9-L15
but here, it the import of `typescript` will resolve to `/node_modules/@biesbjerg/ngx-translate-extract/node_modules/typescript`, and hence uses `typescript@3.7.2`

The problem is that a node has `.type` (integer) property to represent its type, which is used in
https://github.com/microsoft/TypeScript/blob/b58a29b8087445d0b0f647a28c1ad7fb452329e5/src/compiler/utilitiesPublic.ts#L1057-L1059
```typescript
    export function isArrayLiteralExpression(node: Node): node is ArrayLiteralExpression {
        return node.kind === SyntaxKind.ArrayLiteralExpression;
    }
```
to determine the type.

However, this integer value for the same type varies across different typescript versions:
https://github.com/microsoft/TypeScript/blob/v3.5.3/lib/typescript.d.ts#L268
```
ArrayLiteralExpression = 188
```
https://github.com/microsoft/TypeScript/blob/v3.7.2/lib/typescript.d.ts#L271
```
ArrayLiteralExpression = 191
```
To resolve this issue, I suggest to move `typescript` (and `@angular/compiler`) to the `peerDependencies` property, similar to
https://github.com/angular-extensions/lint-rules/blob/6f543846104603ac04f21c4298b5c44aba4318bc/package.json#L19-L35
```json
  "peerDependencies": {
    "tslint": "5.*",
    "typescript": "^3.0.0"
  },
  "dependencies": {
    "@phenomnomnominal/tsquery": "^4.0.0",
    "tsutils-etc": "^1.1.0"
  }
```
In theory, this would be a breaking change, but in reality, `ngx-translate-extract` is only used in angular projects, which ensures that this `peerDependency` requirement is met, so it should not cause problems for any projects except those that don't use angular / typescript.

@biesbjerg if you agree with the proposed solution, I will file a PR with the required changes.

**Comment by biesbjerg** [comment]
@macjohnny thank you for investigating! 

Correct me if I'm wrong, but would moving `typescript` package to `peerDependencies` not result in being locked to whatever version of `typescript` used by `tsquery`?

**Comment by biesbjerg** [comment]
Thank you for the PR! :-)
