### ISSUE TITLE
can @biesbjerg/ngx-translate-extract be installed globally?

### ISSUE THREAD

**Issue by wobeng** [biesbjerg/ngx-translate-extract#196]
Hi 

can @biesbjerg/ngx-translate-extract be installed globally?

**Comment by biesbjerg** [comment]
Sure, that should work

**Comment by wobeng** [comment]
I tried it and it’s not working... keeps asking for dependencies to be installed

**Comment by biesbjerg** [comment]
Oh, I think I know what's up. 

Global install is not supported because it can't reliably parse source code, since it depends on the version of typescript and angular compiler used in the project

More details here:
https://github.com/biesbjerg/ngx-translate-extract/issues/173#issuecomment-609665560

**Comment by wobeng** [comment]
how can I use ngx-translate-extract without it being installed in scripts?

**Comment by biesbjerg** [comment]
It is not a feature I am going to support for the reasons I linked to. Sorry!
