### ISSUE TITLE
Change the default file name

### ISSUE THREAD

**Issue by ocombe** [biesbjerg/ngx-translate-extract#7]
I'd like to extract my strings to en.json and fr.json instead of just template.json.
Do you think it could be possible to change the name of the extracted file?
The best would be to be able to extract to multiple files at the same time, but I'd be ok with just one at a time (and I could make a command on npm for each lang).

PS: I can make a PR if you want

**Comment by biesbjerg** [comment]
Hi!

Custom filename is already possible since https://github.com/biesbjerg/ng2-translate-extract/commit/031890c2a48362ac34c38b0750ee41a94ada3d8d

You can specify full output path including file name.

I've been thinking about allowing multiple --output args, but I need to find another CLI parser that supports it but haven't had the time.

Will leave this ticket open.

**Comment by ocombe** [comment]
Ok, using the complete path works for me, you can close it if you want!

**Comment by biesbjerg** [comment]
Supporting something like this would still be ideal:

```
ng2-translate-extract -o ./my-project/src/assets/i18n/en.json -o ./my-project/src/assets/i18n/fr.json
```

Let this issue serve as a reminder for a day with nothing to do :-p

**Comment by biesbjerg** [comment]
Added in newest release: https://github.com/biesbjerg/ngx-translate-extract/releases/tag/v2.0.0
